<?php

use yii\db\Migration;

/**
 * Class m210813_130322_auto
 */
class m210813_130322_auto extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%auto}}', [
            'id'        => $this->primaryKey(),
            'brand_id'  => $this->integer(),
            'model_id'  => $this->integer(),
            'images'    => $this->text(),
            'add'       => $this->text(),
            'mileage'   => $this->string(),
            'price'     => $this->string(),
            'phone'     => $this->string(),

        ],$tableOptions);

        $this->createIndex('idx_auto_brand', '{{%auto}}', 'brand_id');
        $this->createIndex('idx_auto_model', '{{%auto}}', 'model_id');

        $this->createTable('{{%brand}}', [
            'id'    => $this->primaryKey(),
            'code'  => $this->string(),
            'name'  => $this->string(),
        ],$tableOptions);

        $this->createIndex('idx_brand_code', '{{%brand}}', 'code');

        $brands = [
            ['audi','Audi'],
            ['bmw','BMW'],
            ['chery','Chery'],
            ['chevrolet','Chevrolet'],
            ['citroen','Citroen'],
            ['daewoo','Daewoo'],
            ['datsun','Datsun'],
            ['fiat','Fiat'],
            ['ford','Ford'],
            ['geely','Geely'],
            ['gw','Great Wall'],
            ['haval','Haval'],
            ['honda','Honda'],
            ['hyundai','Hyundai'],
            ['kia','KIA'],
            ['lada','Lada'],
            ['lexus','Lexus'],
            ['lifan','Lifan'],
            ['mazda','Mazda'],
            ['mitsubishi','Mitsubishi'],
            ['nissan','Nissan'],
            ['opel','Opel'],
            ['peugeot','Peugeot'],
            ['ravon','Ravon'],
            ['renault','Renault'],
            ['seat','Seat'],
            ['skoda','Skoda'],
            ['subaru','Subaru'],
            ['suzuki','Suzuki'],
            ['sy','Ssang Yong'],
            ['toyota','Toyota'],
            ['vw','Volkswagen'],
            ['gaz','ГАЗ'],
            ['uaz','УАЗ'],
        ];

        $this->batchInsert('{{%brand}}', ['code','name'], $brands);

        $this->createTable('{{%model}}', [
            'id'    => $this->primaryKey(),
            'code'  => $this->string(),
            'name'  => $this->string(),
        ],$tableOptions);

        $this->createIndex('idx_model_code', '{{%model}}', 'code');

        $models = array(
            'hyundai' => array(
                "Hyundai Accent (С 2000 по 2010г) (с 2011г по н в солярис )",
                "Hyundai Creta с 2016г",
                "Hyundai Elantra 4 поколение с 2006 -2011г",
                "Hyundai Elantra 5 поколение с 2011-2016г",
                "Hyundai Elantra 6 поколение с 2016г",
                "Hyundai Getz(с 2002 - 2011)",
                "Hyundai Grand Starex 8 мест",
                "Hyundai H-1 c 2007г 8 мест",
                "Hyundai I30 (до 2012г)",
                "Hyundai I30 (с 2012 - по наст. время)",
                "Hyundai I40 седан",
                "hyundai ix35 (с 2009 по н в )",
                "Hyundai SantaFe (2007 - 2012)",
                "Hyundai SantaFe (с 2013)",
                "Hyundai SantaFe Classic",
                "Hyundai SantaFe с 2019 4 поколение г. 5мест",
                "Hyundai SantaFe с 2019 4 поколение г. 7мест",
                "Hyundai Solaris 2 с 2017г",
                "Hyundai Solaris I Hatchbaсk (2011-по 2017г)",
                "Hyundai Solaris I sedan(2011-по 2017г)",
                "Hyundai Solaris sedan (60/40) (с 2011 по 2017г.)",
                "Hyundai Sonata 6ср с 2010г",
                "Hyundai Sonata EF 5 кузов(c 2004г по 2008)",
                "Hyundai Sonata NF 5 кузов(c 2004г по 2010)",
                "Hyundai Sonata 7 c 2017 г",
                "Hyundai Tucson (2004-2010)",
                "Hyundai Tucson (2004-2010)",
                "Hyundai Tucson 3поколение с 2016г",
                "Не нашел свою модель",
            ),

            'haval' => array(
                "F7 с 2019г",
                "Не нашел свою модель",
            ),

            'kia' => array(
                "KIA Ceed (с 2007 до 2013г )",
                "Kia Ceed 2 c 2013г по 2018г",
                "Kia Ceed 3 с 2018 по н.в ",
                "KIA Cerato седан (1е поколение с 2003-2008)",
                "KIA Cerato седан(2е поколениес 2009-2012)",
                "KIA Cerato седан,универсал(3е поколение с 2013 по наст время)",
                "Kia Cerato (4е поколение с 2019г)",
                "Kia Optima с 2015г",
                "Kia Picanto 2 c 2011г по 2017г",
                "Kia Picanto 3 c 2017г",
                "Kia rio 2 c 2009 -2011г Хэтч бэк",
                "KIA Rio 3 (HB)Хейчбек 2011 по 2017г)",
                "KIA Rio 3 (SD)Седан 2011 по 2017г",
                "Kia Rio 4 с 2017г",
                "Kia Rio X Line с 2017г (ХБ)",
                "Kia Rio X  с 2020г",
                "Kia Seltos с 2020г",
                "KIA Sorente 3 PRIME (5/7 мест) с 2016г.",
                "KIA Sorento 2 до рестайлинга  (с 2009 до 2012г)",
                "KIA Sorento 2 рестайлинг  с 2012г",
                "KIA Sorento с 2002г по 2009г,EX,LX,TLX",
                "Kia Soul с 2009г до 2014г(1 поколение)",
                "Kia Soul с 2014г(2 поколение)",
                "KIA Soul с 2019г (3 поколение)",
                "KIA Spectra(с 2000 по 2009г)",
                "KIA Sportage 2",
                "KIA Sportage 4 ( с 2016г)",
                "KIA Sportage III ( c 2010 по 2016г)",
                "Kia Venga c 2010г - нв",
                "Kia K5 с 2020г",
                "Не нашел свою модель",
            ),
            'vw' => array(
                "Volkswagen Amarok(пикап) по 2016г",
                "Volkswagen Caravelle Т5 с 2010 по 2015г (8 МЕСТ)",
                "Volkswagen Golf 6",
                "Volkswagen Golf 6 Plus",
                "Volkswagen Golf 7 (5 дверная)",
                "Volkswagen jetta c 2005 (V поколение)",
                "Volkswagen jetta c 2011 (VI поколение)",
                "Volkswagen jetta с 2013 (VI поколение)",
                "Volkswagen lupo c 1998 по 2005г",
                "Volkswagen Multivan Т5 до 2015г 7 мест Comfortline НЕ ТРАНСФОРМЕР",
                "Volkswagen Multivan Т5 до 2015г 7 мест Comfortline ТРАНСФОРМЕР",
                "Volkswagen Multivan Т6 с 2015г",
                "Volkswagen Passat B5( B5+) с 1996г",
                "Volkswagen Passat B6 с 2005 по 2010г",
                "Volkswagen Passat B7 Trendline седан с 2010 по 2015г",
                "Volkswagen Passat B8 седан с 2015г",
                "Volkswagen Polo c 2011 SD (Trendline,Comfortline,Allstar)",
                "Volkswagen Polo рестайлин 2015г SD 60/40 в комплектации Highline",
                "Volkswagen Polo лифтбек с 2020г",
                "Volswagen Tiguan 1 до 2017г",
                "Volswagen Tiguan 2 c 2017г",
                "Volswagen Touareg  с 2011г по н.в.",
                "Не нашел свою модель",
            ),
            'toyota' => array(
                "Toyota Auris (2006-2012г)",
                "Toyota Avensis с 2003 по 2009г седан",
                "Toyota Camry c 2006-2011 г.кузов XV 40 ЛЮКС ",
                "Toyota Camry c 2006-2011 г.Кузов XV 40 НЕ ЛЮКС",
                "Toyota Camry с 2011г по наст. Врем. Кузов XV 50 - 55",
                "Toyota Camry 8 поколение с 2017 - н. в ",
                "Toyota Corolla с 2002г до 2007г седан",
                "Toyota Corolla с 2007 седан 150 кузов",
                "Toyota Corolla с 2014",
                "Toyota Corolla c 2019г",
                "Toyota Fortuner c 2015г 2е поколение",
                "Toyota Highlander с 2008 по 2013г",
                "Toyota Hilux (7 поколение с 2005 до 2015г.)",
                "Toyota Hilux 8 поколение с 2015г",
                "Toyota Land Cruiser Prado 120 5 местный",
                "Toyota Land Cruiser Prado 150 компл. Standart (Eleganse)5 мест",
                "Toyota Land Cruiser Prado 150 компл. Comfort 5 мест",
                "Toyota Land Cruiser Prado 150 рестайлинг с 2017г",
                "Toyota Land Cruiser 100 с 1997г по 2007г 5 местный",
                "Toyota Land Cruiser 200",
                "Toyota RAV-4 c 2013 г.",
                "Toyota RAV-4 с 2000 до 2005г",
                "Toyota RAV-4 с 2005 по 2012г",
                "Toyota RAV 4 с 2019г (5 поколение )",
                "Toyota Verso 2 с 12г-нв",
                "Toyota Yaris х/б с 2005г.",
                "Toyota Camry 70 кузов с 2019 г.",
                "Не нашел свою модель",
            ),
            'nissan' => array(
                "Nissan Almera 16 кузов Седан ( с 2000 по 2006)",
                "Nissan Almera 16 кузов Хэч Бэк ( с 2000 по 2006)",
                "Nissan Almera 2014",
                "Nissan Almera Classic",
                "Nissan Almera Classic",
                "Nissan Juke (с 2010 до 2015г)",
                "Nissan Note (с 2004 по наст)",
                "Nissan Note (с 2004 по наст)",
                "Nissan Pathfinder 3 2005 - 2015г",
                "Nissan Primera P-12 (с 2001 по 2007)",
                "Nissan Qashkai (с 2007 по 2010 или с 2010 до 2013)",
                "Nissan Qashkai +2 ( 5 сидений) 2013",
                "Nissan Qashkai с 2014",
                "Nissan Sentra 2015 с 2012г",
                "Nissan Teana (с 2008 по 2014)",
                "Nissan Terrano с 2014г до 2017г  Элеганс",
                "Nissan Terrano с 2014г до 2017г Комфорт",
                "Nissan Terrano с 2017г",
                "Nissan Tiida седан 1е поколение (с 2004 по 2014г)",
                "Nissan Tiida Хэч бэк 1е поколение (с 2004 по 2014г)",
                "Nissan X Trail T-32 с 2015г",
                "Nissan X Trail Т-30 (с 2001 до 2007)",
                "Nissan X Trail Т-30 (с 2001 до 2007)(коламбия)",
                "Nissan X Trail Т-31 (с 2007 по 2015г)",
                "Не нашел свою модель",
            ),
            'lada' => array(
                "ВАЗ 2107",
                "ВАЗ 2108",
                "ВАЗ 2109",
                "ВАЗ 2110",
                "ВАЗ 2111",
                "ВАЗ 2112",
                "ВАЗ 2113",
                "ВАЗ 2114",
                "ВАЗ 2115",
                "ВАЗ 21213 Нива (3-х дверная) с 94 по 2001г",
                "ВАЗ 21214 Нива (3-х дверная) с 2001г",
                "ВАЗ 2131 (5-и дверная) до 2015г",
                "ВАЗ 2170 Priora Sedan до 2014г",
                "ВАЗ 2170 Priora Sedan с 2014г",
                "ВАЗ 2171 Priora универсал до 2013г",
                "ВАЗ 2171 Priora универсал с 2013г",
                "ВАЗ 2172 Priora HatchBack до 2013г",
                "ВАЗ 2172 Priora HatchBack с 2013г",
                "ВАЗ 2190 Гранта седан или лифтбек",
                "ВАЗ 2190 Гранта с 2018г",
                "ВАЗ 2190 Гранта Кросс с 2018г",
                "Лада 4x4 Urban Niva 3 двери",
                "Лада Niva Travel с 2021г",
                "Лада Largus (5мест ) люкс",
                "Лада Largus (5мест ) норма",
                "Лада Largus 7 мест комплектация Люкс",
                "Лада Largus 7 мест комплектация Норма",
                "Лада Largus 5/7 мест рестайлин с 2021г",
                "Лада Largus Cross",
                "Лада Vesta SW кросс",
                "Лада Vesta седан",
                "Лада Vesta Универсал",
                "Лада XRAY",
                "Лада Калина (Sedan/Hatchback/Wagon) 11193",
                "Лада Калина 2 с 2013г Седан, Хэтчбэк, универсал  БОЛЬШАЯ",
                "Лада Калина 2 с 2013г Седан, Хэтчбэк, универсал МАЛЕНЬКАЯ",
                "Лада Калина Cross БОЛЬШАЯ ",
                "Лада Калина Cross МАЛЕНЬКАЯ",
                "Лада 4x4 Niva 3 дверная с 2020г",
                "Не нашел свою модель",
            ),
            'uaz' => array(
                "УАЗ Patriot до 2014г",
                "УАЗ Patriot до 2014г пикап",
                "Уаз Patriоt с 2014г",
                "Уаз Hunter",
                "Не нашел свою модель",
            ),
            'renault' => array(
                "Renault Arkana c 2019г",
                "Renault Duster Dakar",
                "Renault Duster до 2015г",
                "Renault Duster до 2015г Privilege",
                "Renault Duster с 2015г",
                "Renault Duster с 2017г",
                "Renault Duster 2 поколение с  2021г",
                "Renault Fluence по н.в. седан",
                "Renault Kaptur с 2016г",
                "Renault Koleos 2008г",
                "Renault Logan 2 ПСп Большая",
                "Renault Logan 2 ПСп Маленькая",
                "Renault Logan до 2013",
                "Renault megan 2 Autentic с 2002-2008г",
                "Renault megan 2 Extreme с 2002-2008г",
                "Renault Megan 3 (универсал) (гранд тур не шьем) с 2008г",
                "Renault Megan 3 (хетчбэк) с 2008г",
                "Renault Sandero 1 (спинка 60/40) по н в",
                "Renault Sandero 1 (спинка цельная) по н в",
                "Renault Sandero 2 2014г Acces,Comfort ",
                "Renault Sandero 2 2014г Privilege ",
                "Renault Sandero 2 2014г Stapwey ",
                "Renault Symbol 1 (2002 -2007)",
                "Не нашел свою модель",
            ),
            'citroen' => array(
                'Citroen C4 c 2012 г. седан!!',
                'Citroen C4 Aircross(аналог Mitsubishi ASX c 2010-2013)',
                'Citroen C4 с 2004г - 2011г хэтчбек',
                'Citroen C5 2006 г. (2001-2008) седан',
                'Citrоen Berlingo 2e поколение',
                "Не нашел свою модель",
            ),
            'skoda' => array(
                "Skoda Fabia 2 c 2007",
                "Skoda Octavia A5 (комплектация Elegance )",
                "Skoda Octavia A5(комплектация Ambiente )",
                "Skoda Octavia A7 Hockey Edition",
                "Skoda Oktavia A8 с 2020г",
                "Skoda Octavia Scout A-7",
                "Skoda Octavia Tour (не спорт)",
                "Skoda Oktavia A-7",
                "Skoda Rapid",
                "Skoda Rapid спорт сидения",
                "Skoda superb 2 е пок. с2008 по 2014",
                "Skoda Yeti",
                "Skoda Kodiaq c 2018г",
                "Skoda Karoq I с 2020г",
                "Не нашел свою модель",
            ),
            'ford' => array(
                "Ford EcoSport 2014",
                "Ford EcoSport 2018 г + рестайлинг",
                "Ford Fiesta (c 2008 по 2014г)",
                "Ford Fiesta (c 2015 по н.в.) седан,хэтчбек",
                "Ford Focus 2 (2004-2011) Ghia",
                "Ford Focus 2 3 дверный",
                "Ford Focus 2 komfort и ambiente (2004-2011)",
                "Ford Focus 3 (Комплектация Titanium) с 2011",
                "Ford Focus 3 (Комплектация Trend Sport) с 2011",
                "Ford Focus 3 (Комплектация Trend) с 2011",
                "Ford Fusion (2002 -2012)",
                "Ford Kuga 2 2012 до 2017г",
                "Ford Kuga 2008-2012г(не титаниум)",
                "Ford Kuga c 2017г рестайлинг - кожаный салон",
                "Ford Kuga c 2017г рестайлинг - тканевый салон",
                "Ford Mondeo III c 2000 по 2007 седан (Тренд)",
                "Ford Mondeo III c 2000 по 2007 седан(Титаниум)",
                "Ford Mondeo IV (комплектация Ambiente,Trend)",
                "Ford Mondeo IV( титаниум , гиа )",
                "Ford Mondeo V c 2015г.",
                "Ford Transit",
                "Не нашел свою модель",
            ),
            'mitsubishi' => array(
                "Mitsubishi ASX с 2010 по 2013г",
                "Mitsubishi ASX с 2014",
                "Mitsubishi ASX с 2017",
                "Mitsubishi Galant c 2004г.-н.в.седан",
                "Mitsubishi L200 4 поколениес 2007г до 2013г",
                "Mitsubishi L200 4 поколениес 2013г до 2015г(переходная)",
                "Mitsubishi L200 5 поколение с 2015г",
                "Mitsubishi Lance X СПОРТБЭК ИНВАЙТ до 2012",
                "Mitsubishi Lance X СПОРТБЭК ИНТЕНСЕ до 2012",
                "Mitsubishi Lancer IX Sedan (invite)",
                "Mitsubishi Lancer IX универсал (invite)",
                "Mitsubishi Lancer X до 2012 ИНТЕНСЕ",
                "Mitsubishi Lancer X до 2012 ИНВАЙТ",
                "Mitsubishi Lancer X с 2012 (инвайт)",
                "Mitsubishi Outlander 3 c 2012 по н.в.",
                "Mitsubishi Outlander XL",
                "Mitsubishi Pajero 4 с 2007г",
                "Mitsubishi Pajero Sport 1 (1996г по 2008г)",
                "Mitsubishi Pajero Sport 2 (2008г по н в) автомат",
                "Mitsubishi Pajero Sport 2 (2008г по н.в) механика",
                "Mitsubishi Pajero Sport 3",
                "Не нашел свою модель",
            ),
            'chevrolet' => array(
                "Chevrolet Aveo Hatcback (с 2011 по наст.время)",
                "Chevrolet Aveo Sedan (c 2011 по наст.время)",
                "Chevrolet Aveo до 2011г Т250 седан",
                "Chevrolet Aveo до 2011г Т250 х/б",
                "Chevrolet Captiva (2006- по 2014г и с 2014г по н.в.)",
                "Chevrolet Cruze Hatchback (2011 - по наст.время)",
                "Chevrolet Cruze Sedan (2008 - по наст.время)",
                "Chevrolet Cobalt  2011-2015г",
                "Chevrolet Lacetti Sedan (2003-по наст.время)",
                "Chevrolet Lacetti Хэтчбек , универсал (2003-по наст.время)",
                "Chevrolet Lanos (2005-наст время)",
                "Chevrolet Orlando 5 мест (2010-2012)",
                "Chevrolet Orlando 5 мест с 2013 года",
                "Chevrolet Orlando 7 мест (2010-2012)",
                "Chevrolet Orlando 7 мест с 2013 года",
                "Chevrolet Spark (2010-2013)",
                "Chevrovet Niva до 2009 года",
                "Chevrovet Niva с 2009 по 2014г Бертони",
                "Chevrovet Niva с 2014г по 2016г",
                "Chevrovet Niva с 2016г",
                "Chevrovet Niva с 2017г",
                "Не нашел свою модель",
            ),
            'daewoo' => array(
                'Daewoo Gentra  (копия lacetti sd)',
                'Daewoo Matiz ( с 1998 по н в)',
                'Daewoo Nexia с 2008г по н.в.',
                "Не нашел свою модель",
            ),
            'mazda' => array(
                "Mazda 3 Sedan с 2009-2013",
                "Mazda 3 Sedan (с 2013-по наст.время)",
                "Mazda 3 с 2003 до 2009г Sedan",
                "Mazda 3 с 2003 до 2009г хэтчбек",
                "Mazda 3 хэтчбек с 2009-2013",
                "Mazda 3 хэтчбек с 2019г",
                "Mazda 3 хэтчбек /седан с 2019г",
                "Mazda 6 седан (c 2002 - 2007)",
                "Mazda 6 седан (c 2007 - 2012)",
                "Mazda 6 Hatchback(c 2007-2012) спортбек",
                "Mazda 6 c 2013 года седан",
                "Mazda CX 5 2е поколение с 2017г Актив",
                "Mazda CX 5 2е поколение с 2017г Драйв",
                "Mazda CX 5 до рестайлинга (компл.Active,Supreme) (2012 по 2015г)",
                "Mazda CX 5 компл.Drive (2012- по 2015)",
                "Mazda CX 5 Рестайлинг с 2015г по н.в. (компл.Active,Supreme )",
                "Mazda CX -7 (2006-2012)",
                "Не нашел свою модель",
            ),
            'suzuki' => array(
                'Suzuki Grand Vitara 5 дверный с 2005 года',
                'Suzuki SX 4 HatchBack до 2014г',
                'Suzuki VITARA c 2015 г',
                "Не нашел свою модель",
            ),
            'chery' => array(
                'Cherry Tiggo FL (2013 - по наст. время)',
                'Cherry Tiggo (2006- 2012)',
                "Не нашел свою модель",
            ),
            'honda' => array(
                "Honda Acord (с 2003 по 2008) 7е поколение",
                "Honda Accord 8 седан С 2007г - 2012г",
                "Honda Civic 4D (c 2006 -2011) седан",
                "Honda CR-V (1е поколение 1995-2001гг.)",
                "Honda CR-V (3-е ПОКОЛЕНИЕ 2006-2012г.)",
                "Honda CR-V (4-е ПОКОЛЕНИЕ С 2012г.)",
                "Не нашел свою модель",
            ),
            'audi' => array(
                "Audi 100 (45 кузов) (1991-1994)",
                "Audi A3 sedan кузов 8V, с 2012г",
                "Audi A3 Sportback(хб) 5дверный кузов 8V, с 2012г",
                "Audi A6 (C-4 кузов) седан",
                "Audi A6 (C-5 кузов) (1997-2005)",
                "Audi А6 (45 кузов) (1994-1997)  универсал",
                "Audi А6 (45 кузов) (1994-1997) седан",
                "Audi А6 (45 кузов) (1994-1997) седан Quattro",
                "Audi А6 (45 кузов) (1994-1997) универсал Quattro",
                "Аudi A3 (2003-2008)",
                "Аudi A4 В8 седан с 2007г по 2015г",
                "Аudi A4 В8 универсал с 2007г по 2015г",
                "Audi Q3 (2010-2018)",
                "Не нашел свою модель",
            ),
            'bmw' => array(
                "BMW 318 (90 кузов) (2005-2011)",
                "ВMW 320 (90 кузов) (2005-2011)",
                "BMW X1 ( с 2009г до 2015г ) кузов Е84",
                "BMW X3 F25  с 2010г",
                "Не нашел свою модель",
            ),
            'opel' => array(
                "Opel Antara 2006 - 2011г",
                "Opel Antara c 2011г по н.в.",
                "Opel Astra H ( до 2006г)",
                "Opel Astra H (3 дверная) ( с 2004-по н в ) комплектация космо",
                "Opel Astra H (3 дверная) ( с 2004-по н в ) комплектация энжой",
                "Opel Astra H (5 дверная Hatchback) (с 2004 по н в) комплектация космо",
                "Opel Astra H (5 дверная Hatchback) (с 2004 по н в) комплектация энжой",
                "Opel Astra H (5 дверная универсал )( с 2004 по н в )комплектация космо",
                "Opel Astra H (5 дверная универсал )( с 2004 по н в )комплектация энжой",
                "Opel Astra H (седан ) к-я космо",
                "Opel Astra H (седан ) к-я энжой",
                "Opel Astra J ( ХБ 5 дверный)( с 2009 по наст)",
                "Opel Astra J (3 дверная)( с 2009 по наст)( на спорт не шьем)",
                "Opel Astra J седан",
                "Opel Corsa D (3дверная) с 2006г",
                "Opel Corsa D (5дверная) с 2006г",
                "Opel Insignia седан,универсал,хэтчбек sport turer по н.в.",
                "Opel Meriva A ( с 2003 - 2010г)",
                "Opel Meriva B",
                "Opel Mokka",
                "Opel Zafira B  (5 мест) с 2005г",
                "Opel Zafira B  (средн сид,целое, средн спинка 50/50, средн подлок 7 мест) с 2005г",
                "Не нашел свою модель",
            ),
            'peugeot' => array(
                "Peugeot 308 с 2007г",
                "Peugeot 4007",
                "Peugeot 408",
                "Peugeot Partner 2 c 2008г",
                "Не нашел свою модель",
            ),
            'sy' => array(
                'Ssang Yong Actyon New с 2010 по наст.время',
                'Ssang Yong Kyron',
                "Не нашел свою модель",
            ),
            'lifan' => array(
                "Lifan Solano (С 2009 - до 2016г)",
                "Lifan X-60 с 2016г",
                "Lifan X-60 (с 2011 - 2015г.в.)",
                "Не нашел свою модель",
            ),
            'seat' => array(
                'Seat Ibiza с 2008г х/б',
                "Не нашел свою модель",
            ),
            'geely' => array(
                'Geely Emgrand КУЗОВ EC7 FE-1 до 2016г ',
                'Geele Emgrand X7 с 2013г',
                'Geely Coolray I с 2020г',
                "Не нашел свою модель",
            ),
            'gw' => array(
                'Great Wall Hover H3(H5) с 2011г',
                "Не нашел свою модель",
            ),
            'lexus' => array(
                'Lexus NX 200',
                'Lexus RX 350 с 2003-2009 джип',
                'Lexus RX 350 с 2009г-2015г',
                "Не нашел свою модель",
            ),
            'subaru' => array(
                'Subaru Forester 3 (2008-2012)',
                'Subaru Impreza 3 с 2007-2011',
                "Не нашел свою модель",
            ),
            'fiat' => array(
                'Fiat Albea',
                "Не нашел свою модель",
            ),
            'datsun' => array(
                'Datsun On-Do',
                "Не нашел свою модель",
            ),
            'gaz' => array(
                'Газ 3110',
                "Не нашел свою модель",
            ),
            'ravon' => array(
                'Ravon R4 с 16г.в.',
                "Не нашел свою модель",
            )
        );

        $insert=[];
        foreach ($models as $key=>$model){
            foreach ($model as $item){
                echo $key.'='.$item."\n";
                $insert[]=[$key,$item];
            }
        }
        $this->batchInsert('{{%model}}', ['code','name'], $insert);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropIndex('idx_auto_brand', '{{%auto}}');
        $this->dropIndex('idx_auto_model', '{{%auto}}');
        $this->dropIndex('idx_brand_code','{{%brand}}');
        $this->dropIndex('idx_model_code','{{%model}}');

        $this->dropTable('{{%auto}}');
        $this->dropTable('{{%brand}}');
        $this->dropTable('{{%model}}');
    }

}
